spring:
  config:
    activate:
      on-profile: dev
  datasource:
    hikari:
      maximum-pool-size: 3
      connection-timeout: 10000
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://ec2-54-72-155-238.eu-west-1.compute.amazonaws.com:5432/dof83lm03isin
    driver-class-name: org.postgresql.Driver
    username: dczeokrkqqpqoy
    password: 9fc0edbc48b76af82acda4862e2aac1326c55b40ed1bf9a7000161ba90e36737
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
jwt:
  token:
    secret: answerqwerty