spring:
  config:
    activate:
      on-profile: default
  datasource:
    hikari:
      maximum-pool-size: 3
      connection-timeout: 10000
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://ec2-54-72-155-238.eu-west-1.compute.amazonaws.com:5432/dbqtgi4vd8s3s4
    driver-class-name: org.postgresql.Driver
    username: faiasdqftxbjsr
    password: a56859a38e5d2634e0eab825d19e160f63dbe026b10012322e01c3891254dc23
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
jwt:
  token:
    secret: answerqwerty
server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false
